configfile: "config/config.yaml"

##### load rules #####

include: "rules/common.smk"
include: "rules/star.smk"
include: "rules/trim_reads.smk"
include: "rules/kallisto.smk"



# workdir: config['outdir']

rule all:
    input:
        "psuedoalignment_stats.html",
        "star_alignment_stats.html",
        #expand("kallisto_quant/{replicate}/abundance.h5", replicate=REPLICATES["replicate_name"])
    