configfile: "config/config.yaml"

##### load rules #####

include: "rules/common.smk"
include: "rules/index_genome.smk"
include: "rules/trim_reads.smk"
include: "rules/kallisto.smk"



# workdir: config['outdir']

rule all:
    input:
        expand(directory("kallisto_quant/{replicate}/abundance.h5"), replicate=REPLICATES["replicate_name"])
       # expand("trimmed_reads/{replicate}_P_R1.fastq.gz", replicate=REPLICATES["replicate_name"])