replicates: /home/eab77806/sunflower_stress/config/replicates2.tsv

transcriptome: /scratch/eab77806/salt_stress/genomes/Ha412/Ha412HO_v2_braker.cds.fa

index_prefix: /scratch/eab77806/salt_stress/genomes/Ha412/Ha412HO_v2_braker.transcripts.idx